# Generated by Django 2.2.5 on 2019-10-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20191004_1252'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='eventmodels',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='group_process',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='indicator',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='memberprocess',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='position',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='risk',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='scenario',
            managers=[
            ],
        ),
    ]
