# Generated by Django 2.2.5 on 2019-10-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20191009_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='group',
        ),
        migrations.AddField(
            model_name='process',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='process.Process', verbose_name='base'),
        ),
    ]
