# Generated by Django 2.2.1 on 2019-10-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20191017_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventmodels',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.Expense', verbose_name='Затрата'),
        ),
    ]
