# Generated by Django 2.2.1 on 2019-10-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20191023_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='number',
        ),
    ]
