# Generated by Django 2.2.1 on 2019-10-24 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_remove_process_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodels',
            name='expense',
        ),
        migrations.AddField(
            model_name='eventmodels',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='Затрата'),
            preserve_default=False,
        ),
    ]
