# Generated by Django 3.0.2 on 2020-04-30 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_auto_20191024_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodels',
            name='process',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='Затрата'),
        ),
    ]
